window.WAWO_CATALOGUE = [
  {
    "id": "10-001",
    "page": 10,
    "title": "Executive leather accessories",
    "category": "gifts",
    "group": "Executive gifts",
    "description": "Wallets, passport covers and luggage tags for business travel and executive gifting.",
    "branding": "Laser engraving, debossing and foil stamping",
    "image": "assets/catalogue/products/10-001.webp",
    "width": 850,
    "height": 869
  },
  {
    "id": "11-002",
    "page": 11,
    "title": "Hospitality & wellness gift collection",
    "category": "gifts",
    "group": "Hospitality & wellness",
    "description": "Coordinated hospitality and relaxation gifts, from towels and candles to drinkware and personal accessories.",
    "branding": "UV printing, laser engraving and embroidery",
    "image": "assets/catalogue/products/11-002.webp",
    "width": 865,
    "height": 1052
  },
  {
    "id": "12-003",
    "page": 12,
    "title": "School, campus & training merchandise",
    "category": "events",
    "group": "Campus & training",
    "description": "Coordinated bags, apparel, notebooks, drinkware and lanyards for orientations, workshops and student communities.",
    "branding": "Screen printing, DTF printing and embroidery",
    "image": "assets/catalogue/products/12-003.webp",
    "width": 941,
    "height": 1041
  },
  {
    "id": "13-004",
    "page": 13,
    "title": "Employee welcome kit",
    "category": "gifts",
    "group": "Employee kits",
    "description": "A coordinated first-day kit with a backpack, tote, notebook, bottle, lanyard and presentation box.",
    "branding": "Custom branding across the kit",
    "image": "assets/catalogue/products/13-004.webp",
    "width": 956,
    "height": 1008
  },
  {
    "id": "14-005",
    "page": 14,
    "title": "Seasonal gift hamper",
    "category": "gifts",
    "group": "Seasonal gifting",
    "description": "Curated hampers for celebrations, end-of-year appreciation and client gifting.",
    "branding": "Custom packaging and product branding",
    "image": "assets/catalogue/products/14-005.webp",
    "width": 865,
    "height": 1052
  },
  {
    "id": "15-006",
    "page": 15,
    "title": "Double-wall vacuum bottle & tumbler",
    "category": "gifts",
    "group": "Drinkware",
    "description": "Temperature-retaining bottles and tumblers for executive gifts, staff kits and events.",
    "branding": "Screen printing, UV printing and laser engraving",
    "image": "assets/catalogue/products/15-006.webp",
    "width": 1016,
    "height": 1008
  },
  {
    "id": "16-007",
    "page": 16,
    "title": "Event pack essentials",
    "category": "events",
    "group": "Event merchandise",
    "description": "T-shirts, caps, lanyards, wristbands, totes and bottles in a coordinated attendee pack.",
    "branding": "Screen printing, DTF printing, embroidery and UV printing",
    "image": "assets/catalogue/products/16-007.webp",
    "width": 865,
    "height": 1030
  },
  {
    "id": "17-008",
    "page": 17,
    "title": "Crew & volunteer merchandise",
    "category": "events",
    "group": "Event merchandise",
    "description": "Branded T-shirts, caps and carry items to identify teams and volunteers at events.",
    "branding": "Screen printing, DTF printing and embroidery",
    "image": "assets/catalogue/products/17-008.webp",
    "width": 971,
    "height": 441
  },
  {
    "id": "18-009",
    "page": 18,
    "title": "Everyday promotional essentials",
    "category": "events",
    "group": "Event merchandise",
    "description": "Bottles, umbrellas, drawstring bags, keyrings, speakers and pens for campaign giveaways.",
    "branding": "Pad printing, screen printing, UV printing and laser engraving",
    "image": "assets/catalogue/products/18-009.webp",
    "width": 834,
    "height": 1009
  },
  {
    "id": "19-010",
    "page": 19,
    "title": "Custom packaging & gift presentation",
    "category": "packaging",
    "group": "Gift presentation",
    "description": "Coordinated boxes, bags, tissue and printed inserts for product launches and gifting.",
    "branding": "Full-colour printing, UV printing, foil stamping and embossing",
    "image": "assets/catalogue/products/19-010.webp",
    "width": 833,
    "height": 1041
  },
  {
    "id": "20-011",
    "page": 20,
    "title": "Executive notebook, pen & bottle gift set",
    "category": "gifts",
    "group": "Executive gifts",
    "description": "A presentation-box gift set for onboarding, recognition and client appreciation.",
    "branding": "UV printing, laser engraving, debossing and foil stamping",
    "image": "assets/catalogue/products/20-011.webp",
    "width": 834,
    "height": 1009
  },
  {
    "id": "21-012",
    "page": 21,
    "title": "Executive & everyday accessories",
    "category": "gifts",
    "group": "Executive gifts",
    "description": "Notebook, umbrella, pen, keyring and accessory options for corporate gifting programmes.",
    "branding": "Screen printing, UV printing, laser engraving and embossing",
    "image": "assets/catalogue/products/21-012.webp",
    "width": 941,
    "height": 998
  },
  {
    "id": "22-013",
    "page": 22,
    "title": "Premium gift boxes & gift bags",
    "category": "packaging",
    "group": "Gift presentation",
    "description": "Presentation packaging for retail, client gifts and branded merchandise.",
    "branding": "Full-colour printing, UV printing, foil stamping and embossing",
    "image": "assets/catalogue/products/22-013.webp",
    "width": 834,
    "height": 976
  },
  {
    "id": "24-014",
    "page": 24,
    "title": "Mailer bags",
    "category": "packaging",
    "group": "Mailers & pouches",
    "description": "Branded mailing bags for e-commerce, product fulfilment, PR drops and retail deliveries.",
    "branding": "Full-colour printing",
    "image": "assets/catalogue/products/24-014.webp",
    "width": 819,
    "height": 923
  },
  {
    "id": "25-015",
    "page": 25,
    "title": "Frosted ziplock bags",
    "category": "packaging",
    "group": "Mailers & pouches",
    "description": "Reusable frosted pouches for garments, samples, accessories and cosmetics.",
    "branding": "Full-colour printing",
    "image": "assets/catalogue/products/25-015.webp",
    "width": 804,
    "height": 859
  },
  {
    "id": "26-016",
    "page": 26,
    "title": "Mailer bags with handles",
    "category": "packaging",
    "group": "Mailers & pouches",
    "description": "Handled mailing bags for branded deliveries and retail purchases.",
    "branding": "Screen printing, UV printing and full-colour printing",
    "image": "assets/catalogue/products/26-016.webp",
    "width": 819,
    "height": 891
  },
  {
    "id": "27-017",
    "page": 27,
    "title": "Drawstring packaging bags",
    "category": "packaging",
    "group": "Retail bags",
    "description": "Drawstring carry bags for product packaging, gifting and retail.",
    "branding": "Screen printing, UV printing and sublimation",
    "image": "assets/catalogue/products/27-017.webp",
    "width": 850,
    "height": 891
  },
  {
    "id": "28-018",
    "page": 28,
    "title": "Matte loop bags",
    "category": "packaging",
    "group": "Retail bags",
    "description": "Loop-handle bags in a range of colours for retail packaging and giveaways.",
    "branding": "Custom printing",
    "image": "assets/catalogue/products/28-018.webp",
    "width": 819,
    "height": 891
  },
  {
    "id": "29-019",
    "page": 29,
    "title": "Gusset bags",
    "category": "packaging",
    "group": "Retail bags",
    "description": "Structured bags with extra capacity for retail products, merchandise and promotional kits.",
    "branding": "Full-colour printing",
    "image": "assets/catalogue/products/29-019.webp",
    "width": 744,
    "height": 827
  },
  {
    "id": "30-020",
    "page": 30,
    "title": "Bubble mailer bags",
    "category": "packaging",
    "group": "Mailers & pouches",
    "description": "Cushioned mailers for protective packaging and branded delivery.",
    "branding": "Custom printing",
    "image": "assets/catalogue/products/30-020.webp",
    "width": 880,
    "height": 891
  },
  {
    "id": "31-021",
    "page": 31,
    "title": "Lifestyle & wellness gifts",
    "category": "gifts",
    "group": "Hospitality & wellness",
    "description": "Coffee accessories, candles, drinkware, towels and personal wellness gifts.",
    "branding": "UV printing, laser engraving, screen printing and embroidery",
    "image": "assets/catalogue/products/31-021.webp",
    "width": 865,
    "height": 1052
  },
  {
    "id": "32-022",
    "page": 32,
    "title": "Curated corporate gift bundles",
    "category": "gifts",
    "group": "Gift bundles",
    "description": "Executive, team and event bundles tailored to your audience and occasion.",
    "branding": "Coordinated product and packaging branding",
    "image": "assets/catalogue/products/32-022.webp",
    "width": 592,
    "height": 1008
  },
  {
    "id": "34-023",
    "page": 34,
    "title": "Power banks & charging essentials",
    "category": "gifts",
    "group": "Technology",
    "description": "Power banks, cables and charging essentials for connected working days.",
    "branding": "UV printing, screen printing and laser engraving",
    "image": "assets/catalogue/products/34-023.webp",
    "width": 789,
    "height": 966
  },
  {
    "id": "35-024",
    "page": 35,
    "title": "USB drives & memory accessories",
    "category": "gifts",
    "group": "Technology",
    "description": "Compact branded memory accessories for conferences, campaigns and business use.",
    "branding": "UV printing, pad printing and laser engraving",
    "image": "assets/catalogue/products/35-024.webp",
    "width": 789,
    "height": 976
  },
  {
    "id": "36-025",
    "page": 36,
    "title": "Wireless audio & charging accessories",
    "category": "gifts",
    "group": "Technology",
    "description": "Wireless speakers, earbuds and charging accessories for contemporary corporate gifts.",
    "branding": "UV printing, screen printing, laser engraving and debossing",
    "image": "assets/catalogue/products/36-025.webp",
    "width": 834,
    "height": 1020
  },
  {
    "id": "37-026",
    "page": 37,
    "title": "Desk tech & phone stands",
    "category": "gifts",
    "group": "Technology",
    "description": "Desktop phone and tablet stands for offices, home desks and staff gift packs.",
    "branding": "Custom branding",
    "image": "assets/catalogue/products/37-026.webp",
    "width": 728,
    "height": 504
  },
  {
    "id": "38-027",
    "page": 38,
    "title": "Mobile & travel tech accessories",
    "category": "gifts",
    "group": "Technology",
    "description": "Compact travel adapters, mobile accessories and tech organisers for work and travel.",
    "branding": "UV printing, pad printing and laser engraving",
    "image": "assets/catalogue/products/38-027.webp",
    "width": 1047,
    "height": 591
  },
  {
    "id": "40-028",
    "page": 40,
    "title": "Premium hardcover notebooks",
    "category": "stationery",
    "group": "Notebooks & diaries",
    "description": "A refined notebook for meetings, planning, onboarding and executive gifting.",
    "branding": "UV printing, screen printing, debossing and foil stamping",
    "image": "assets/catalogue/products/40-028.webp",
    "width": 850,
    "height": 933
  },
  {
    "id": "41-029",
    "page": 41,
    "title": "Softcover diaries & planners",
    "category": "stationery",
    "group": "Notebooks & diaries",
    "description": "Flexible everyday planning tools for work, study and branded gift packs.",
    "branding": "Screen printing, UV printing and debossing",
    "image": "assets/catalogue/products/41-029.webp",
    "width": 834,
    "height": 1009
  },
  {
    "id": "42-030",
    "page": 42,
    "title": "Branded pens & writing tools",
    "category": "stationery",
    "group": "Writing tools",
    "description": "Metal, bamboo and promotional writing tools that keep your brand in hand.",
    "branding": "Screen printing, UV printing and laser engraving",
    "image": "assets/catalogue/products/42-030.webp",
    "width": 865,
    "height": 1030
  },
  {
    "id": "43-031",
    "page": 43,
    "title": "Desk accessories & memo essentials",
    "category": "stationery",
    "group": "Desk essentials",
    "description": "Pen holders, memo cubes, sticky notes and desk companions for everyday work.",
    "branding": "Custom printing",
    "image": "assets/catalogue/products/43-031.webp",
    "width": 971,
    "height": 1030
  },
  {
    "id": "44-032",
    "page": 44,
    "title": "Calendars & planning tools",
    "category": "stationery",
    "group": "Calendars",
    "description": "Desk and wall calendars for year-round visibility at work and at home.",
    "branding": "Full-colour printing, screen printing and UV printing",
    "image": "assets/catalogue/products/44-032.webp",
    "width": 895,
    "height": 1030
  },
  {
    "id": "45-033",
    "page": 45,
    "title": "Everyday water bottles",
    "category": "gifts",
    "group": "Drinkware",
    "description": "Reusable bottles for offices, events, campuses and promotional campaigns.",
    "branding": "Screen printing, UV printing and sublimation",
    "image": "assets/catalogue/products/45-033.webp",
    "width": 834,
    "height": 1008
  },
  {
    "id": "46-034",
    "page": 46,
    "title": "Signature ceramic mugs",
    "category": "gifts",
    "group": "Drinkware",
    "description": "Classic ceramic mugs for desks, hospitality spaces and everyday brand visibility.",
    "branding": "Sublimation, screen printing and UV printing",
    "image": "assets/catalogue/products/46-034.webp",
    "width": 850,
    "height": 419
  },
  {
    "id": "47-035",
    "page": 47,
    "title": "Travel mugs & handled tumblers",
    "category": "gifts",
    "group": "Drinkware",
    "description": "Handled drinkware and travel cups for commuting, desks and on-the-go routines.",
    "branding": "Screen printing, UV printing and laser engraving",
    "image": "assets/catalogue/products/47-035.webp",
    "width": 819,
    "height": 934
  },
  {
    "id": "48-036",
    "page": 48,
    "title": "Flasks, coffee presses & tea accessories",
    "category": "gifts",
    "group": "Drinkware",
    "description": "Drinkware and serving accessories for hospitality, workplaces and gifting.",
    "branding": "Laser engraving, screen printing and UV printing",
    "image": "assets/catalogue/products/48-036.webp",
    "width": 668,
    "height": 998
  },
  {
    "id": "51-037",
    "page": 51,
    "title": "Crossbody & utility pouches",
    "category": "bags",
    "group": "Pouches",
    "description": "Compact bags for everyday essentials, branded merchandise and travel.",
    "branding": "DTF printing, embroidery and heat transfer",
    "image": "assets/catalogue/products/51-037.webp",
    "width": 865,
    "height": 1041
  },
  {
    "id": "52-038",
    "page": 52,
    "title": "Signature cotton tote bags",
    "category": "bags",
    "group": "Totes & shoppers",
    "description": "Reusable everyday carriers with a generous surface for your brand.",
    "branding": "Screen printing, DTF printing and heat transfer",
    "image": "assets/catalogue/products/52-038.webp",
    "width": 887,
    "height": 880
  },
  {
    "id": "53-039",
    "page": 53,
    "title": "Jute & non-woven shoppers",
    "category": "bags",
    "group": "Totes & shoppers",
    "description": "Practical shoppers for retail, events and reusable branded packaging.",
    "branding": "Screen printing, DTF printing and heat transfer",
    "image": "assets/catalogue/products/53-039.webp",
    "width": 880,
    "height": 944
  },
  {
    "id": "54-040",
    "page": 54,
    "title": "Drawstring event bags",
    "category": "bags",
    "group": "Event bags",
    "description": "Lightweight storage for conferences, sports days, schools and activations.",
    "branding": "Screen printing, DTF printing and sublimation",
    "image": "assets/catalogue/products/54-040.webp",
    "width": 834,
    "height": 998
  },
  {
    "id": "55-041",
    "page": 55,
    "title": "Laptop sleeves & corporate laptop bags",
    "category": "bags",
    "group": "Work & travel",
    "description": "Protective laptop sleeves and carry bags for staff, meetings and business travel.",
    "branding": "Custom printing and embroidery",
    "image": "assets/catalogue/products/55-041.webp",
    "width": 774,
    "height": 987
  },
  {
    "id": "56-042",
    "page": 56,
    "title": "Everyday corporate backpacks",
    "category": "bags",
    "group": "Work & travel",
    "description": "Branded backpacks for staff, students, travel and everyday use.",
    "branding": "Custom printing and embroidery",
    "image": "assets/catalogue/products/56-042.webp",
    "width": 774,
    "height": 322
  },
  {
    "id": "57-043",
    "page": 57,
    "title": "Premium sweatshirts & hoodies",
    "category": "merchandise",
    "group": "Apparel",
    "description": "Comfortable branded layers for teams, launches, campuses and merchandise collections.",
    "branding": "DTF printing, embroidery and screen printing",
    "image": "assets/catalogue/products/57-043.webp",
    "width": 895,
    "height": 1008
  },
  {
    "id": "58-044",
    "page": 58,
    "title": "Corporate shirts & workwear",
    "category": "merchandise",
    "group": "Workwear",
    "description": "Corporate shirts and workwear for a consistent team appearance.",
    "branding": "Embroidery, DTF printing and heat transfer",
    "image": "assets/catalogue/products/58-044.webp",
    "width": 789,
    "height": 987
  },
  {
    "id": "59-045",
    "page": 59,
    "title": "Premium cotton T-shirts",
    "category": "merchandise",
    "group": "Apparel",
    "description": "Everyday branded T-shirts for businesses, teams and events.",
    "branding": "Screen printing, DTF printing and embroidery",
    "image": "assets/catalogue/products/59-045.webp",
    "width": 1089,
    "height": 542
  },
  {
    "id": "60-046",
    "page": 60,
    "title": "Signature polo shirts",
    "category": "merchandise",
    "group": "Apparel",
    "description": "Polos for staff uniforms, corporate events and branded merchandise.",
    "branding": "Embroidery, screen printing and DTF printing",
    "image": "assets/catalogue/products/60-046.webp",
    "width": 895,
    "height": 966
  },
  {
    "id": "61-047",
    "page": 61,
    "title": "Six-panel face caps",
    "category": "merchandise",
    "group": "Caps & headwear",
    "description": "Classic face caps for promotional campaigns, uniforms and events.",
    "branding": "Embroidery, screen printing and DTF printing",
    "image": "assets/catalogue/products/61-047.webp",
    "width": 1016,
    "height": 462
  },
  {
    "id": "62-048",
    "page": 62,
    "title": "Branded bucket hats",
    "category": "merchandise",
    "group": "Caps & headwear",
    "description": "Contemporary bucket hats for campaigns, merchandise drops and casual teams.",
    "branding": "Embroidery, DTF printing and screen printing",
    "image": "assets/catalogue/products/62-048.webp",
    "width": 819,
    "height": 451
  },
  {
    "id": "63-049",
    "page": 63,
    "title": "Hoodies, sweatshirts & zip jackets",
    "category": "merchandise",
    "group": "Apparel",
    "description": "Coordinated hoodies, sweatshirts and zip jackets with plain and branded options.",
    "branding": "DTF printing, screen printing and embroidery",
    "image": "assets/catalogue/products/63-049.webp",
    "width": 941,
    "height": 1019
  },
  {
    "id": "64-050",
    "page": 64,
    "title": "Caps & headwear range",
    "category": "merchandise",
    "group": "Caps & headwear",
    "description": "Baseball caps, five-panel caps and bucket hats in coordinated colour options.",
    "branding": "Embroidery and custom printing",
    "image": "assets/catalogue/products/64-050.webp",
    "width": 850,
    "height": 1009
  },
  {
    "id": "65-051",
    "page": 65,
    "title": "Premium corporate gift bundles",
    "category": "gifts",
    "group": "Gift bundles",
    "description": "Executive, team and event sets with bags, notebooks and drinkware.",
    "branding": "Coordinated product and packaging branding",
    "image": "assets/catalogue/products/65-051.webp",
    "width": 433,
    "height": 981
  },
  {
    "id": "23-052",
    "page": 23,
    "title": "Corrugated shipping box",
    "category": "packaging",
    "group": "Boxes",
    "description": "Protective corrugated packaging for product shipping and deliveries.",
    "branding": "Custom printing and packaging finishes",
    "image": "assets/catalogue/products/23-052.webp",
    "width": 456,
    "height": 291
  },
  {
    "id": "23-053",
    "page": 23,
    "title": "Corrugated mailer box",
    "category": "packaging",
    "group": "Boxes",
    "description": "Fold-over mailer packaging for e-commerce orders and branded unboxing.",
    "branding": "Custom printing and packaging finishes",
    "image": "assets/catalogue/products/23-053.webp",
    "width": 455,
    "height": 291
  },
  {
    "id": "23-054",
    "page": 23,
    "title": "Rigid lift-off lid gift box",
    "category": "packaging",
    "group": "Boxes",
    "description": "Two-piece rigid presentation boxes for premium gifts.",
    "branding": "Custom printing and packaging finishes",
    "image": "assets/catalogue/products/23-054.webp",
    "width": 456,
    "height": 291
  },
  {
    "id": "23-055",
    "page": 23,
    "title": "Magnetic closure gift box",
    "category": "packaging",
    "group": "Boxes",
    "description": "Presentation boxes with a hinged magnetic closure.",
    "branding": "Custom printing and packaging finishes",
    "image": "assets/catalogue/products/23-055.webp",
    "width": 456,
    "height": 290
  },
  {
    "id": "23-056",
    "page": 23,
    "title": "Window gift box",
    "category": "packaging",
    "group": "Boxes",
    "description": "Gift packaging with a display window to show the product inside.",
    "branding": "Custom printing and packaging finishes",
    "image": "assets/catalogue/products/23-056.webp",
    "width": 455,
    "height": 290
  },
  {
    "id": "23-057",
    "page": 23,
    "title": "Kraft handle gift box",
    "category": "packaging",
    "group": "Boxes",
    "description": "Carry-handle gift boxes for retail and event presentation.",
    "branding": "Custom printing and packaging finishes",
    "image": "assets/catalogue/products/23-057.webp",
    "width": 456,
    "height": 290
  },
  {
    "id": "66-058",
    "page": 66,
    "title": "Full bus wrap",
    "category": "vehicles",
    "group": "Vehicle branding",
    "description": "Full-body bus graphics for prominent visibility on the road.",
    "branding": "Vehicle vinyl graphics",
    "image": "assets/catalogue/products/66-058.webp",
    "width": 483,
    "height": 306
  },
  {
    "id": "66-059",
    "page": 66,
    "title": "Partial bus branding",
    "category": "vehicles",
    "group": "Vehicle branding",
    "description": "Branded panels that work with the vehicle’s existing colour.",
    "branding": "Vehicle vinyl graphics",
    "image": "assets/catalogue/products/66-059.webp",
    "width": 483,
    "height": 306
  },
  {
    "id": "66-060",
    "page": 66,
    "title": "Commercial bus branding",
    "category": "vehicles",
    "group": "Vehicle branding",
    "description": "Graphics for commercial and passenger transport vehicles.",
    "branding": "Vehicle vinyl graphics",
    "image": "assets/catalogue/products/66-060.webp",
    "width": 483,
    "height": 306
  },
  {
    "id": "66-061",
    "page": 66,
    "title": "Full car wrap",
    "category": "vehicles",
    "group": "Vehicle branding",
    "description": "Full exterior graphics for branded cars and campaigns.",
    "branding": "Vehicle vinyl graphics",
    "image": "assets/catalogue/products/66-061.webp",
    "width": 483,
    "height": 306
  },
  {
    "id": "66-062",
    "page": 66,
    "title": "Car door branding",
    "category": "vehicles",
    "group": "Vehicle branding",
    "description": "Logo and contact graphics on vehicle doors.",
    "branding": "Vehicle vinyl graphics",
    "image": "assets/catalogue/products/66-062.webp",
    "width": 483,
    "height": 306
  },
  {
    "id": "66-063",
    "page": 66,
    "title": "Fleet branding",
    "category": "vehicles",
    "group": "Vehicle branding",
    "description": "A coordinated visual identity across your company vehicles.",
    "branding": "Vehicle vinyl graphics",
    "image": "assets/catalogue/products/66-063.webp",
    "width": 483,
    "height": 306
  },
  {
    "id": "67-064",
    "page": 67,
    "title": "Reception branding — WAWO concept",
    "category": "office",
    "group": "Office branding",
    "description": "A branded reception and arrival point for your workplace.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/67-064.webp",
    "width": 483,
    "height": 333
  },
  {
    "id": "67-065",
    "page": 67,
    "title": "Office wall graphics — WAWO concept",
    "category": "office",
    "group": "Office branding",
    "description": "Custom wall graphics that carry your brand through the office.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/67-065.webp",
    "width": 480,
    "height": 333
  },
  {
    "id": "67-066",
    "page": 67,
    "title": "Glass partition branding — WAWO concept",
    "category": "office",
    "group": "Office branding",
    "description": "Branded glass graphics for partitions and workspace identity.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/67-066.webp",
    "width": 483,
    "height": 333
  },
  {
    "id": "67-067",
    "page": 67,
    "title": "Wayfinding & directional signs — WAWO concept",
    "category": "office",
    "group": "Office branding",
    "description": "Coordinated signs to help visitors navigate your space.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/67-067.webp",
    "width": 483,
    "height": 333
  },
  {
    "id": "67-068",
    "page": 67,
    "title": "Meeting room branding — WAWO concept",
    "category": "office",
    "group": "Office branding",
    "description": "Wall and glass branding for meeting and collaboration spaces.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/67-068.webp",
    "width": 480,
    "height": 333
  },
  {
    "id": "67-069",
    "page": 67,
    "title": "Office door & room signs — WAWO concept",
    "category": "office",
    "group": "Office branding",
    "description": "Consistent identification for offices, rooms and facilities.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/67-069.webp",
    "width": 483,
    "height": 333
  },
  {
    "id": "68-070",
    "page": 68,
    "title": "Reception branding — Exito concept",
    "category": "office",
    "group": "Office branding",
    "description": "A branded reception and arrival point for your workplace.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/68-070.webp",
    "width": 713,
    "height": 665
  },
  {
    "id": "68-071",
    "page": 68,
    "title": "Office wall graphics — Exito concept",
    "category": "office",
    "group": "Office branding",
    "description": "Custom wall graphics that carry your brand through the office.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/68-071.webp",
    "width": 698,
    "height": 280
  },
  {
    "id": "68-072",
    "page": 68,
    "title": "Glass partition branding — Exito concept",
    "category": "office",
    "group": "Office branding",
    "description": "Branded glass graphics for partitions and workspace identity.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/68-072.webp",
    "width": 698,
    "height": 269
  },
  {
    "id": "68-073",
    "page": 68,
    "title": "Wayfinding & directional signs — Exito concept",
    "category": "office",
    "group": "Office branding",
    "description": "Coordinated signs to help visitors navigate your space.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/68-073.webp",
    "width": 198,
    "height": 258
  },
  {
    "id": "68-074",
    "page": 68,
    "title": "Meeting room branding — Exito concept",
    "category": "office",
    "group": "Office branding",
    "description": "Wall and glass branding for meeting and collaboration spaces.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/68-074.webp",
    "width": 259,
    "height": 258
  },
  {
    "id": "68-075",
    "page": 68,
    "title": "Office door & room signs — Exito concept",
    "category": "office",
    "group": "Office branding",
    "description": "Consistent identification for offices, rooms and facilities.",
    "branding": "Custom signage, vinyl and wall graphics",
    "image": "assets/catalogue/products/68-075.webp",
    "width": 183,
    "height": 258
  },
  {
    "id": "69-076",
    "page": 69,
    "title": "Conference stage & backdrop",
    "category": "events",
    "group": "Conference branding",
    "description": "Large-format stage graphics and a coordinated conference backdrop.",
    "branding": "Custom large-format printing",
    "image": "assets/catalogue/products/69-076.webp",
    "width": 1200,
    "height": 240
  },
  {
    "id": "69-077",
    "page": 69,
    "title": "Registration desk branding",
    "category": "events",
    "group": "Conference branding",
    "description": "Branded registration desks and arrival signage for event guests.",
    "branding": "Custom large-format printing",
    "image": "assets/catalogue/products/69-077.webp",
    "width": 297,
    "height": 280
  },
  {
    "id": "69-078",
    "page": 69,
    "title": "Photo wall & event backdrop",
    "category": "events",
    "group": "Conference branding",
    "description": "Branded photography areas for attendees and speakers.",
    "branding": "Custom large-format printing",
    "image": "assets/catalogue/products/69-078.webp",
    "width": 281,
    "height": 280
  },
  {
    "id": "69-079",
    "page": 69,
    "title": "Exhibition booth branding",
    "category": "events",
    "group": "Conference branding",
    "description": "Branded exhibition stands and counters for conferences and activations.",
    "branding": "Custom large-format printing",
    "image": "assets/catalogue/products/69-079.webp",
    "width": 281,
    "height": 280
  },
  {
    "id": "69-080",
    "page": 69,
    "title": "Event wayfinding & display banners",
    "category": "events",
    "group": "Conference branding",
    "description": "Freestanding directions and information displays for conference guests.",
    "branding": "Custom large-format printing",
    "image": "assets/catalogue/products/69-080.webp",
    "width": 289,
    "height": 280
  },
  {
    "id": "69-081",
    "page": 69,
    "title": "Conference attendee merchandise",
    "category": "events",
    "group": "Conference branding",
    "description": "Coordinated totes, badges, lanyards and printed attendee materials.",
    "branding": "Custom large-format printing",
    "image": "assets/catalogue/products/69-081.webp",
    "width": 297,
    "height": 280
  }
];
