const categories={
 gifts:['Corporate Gifts','Explore executive gifts, employee kits, drinkware, technology and thoughtful seasonal bundles.'],
 merchandise:['Apparel & Merchandise','T-shirts, polos, workwear and headwear, with the finish and colours that fit your team.'],
 stationery:['Notebooks & Stationery','Notebooks, diaries, writing tools and desk essentials for ideas and everyday work.'],
 packaging:['Packaging & Gift Sets','From protective delivery packaging to premium gift presentation. Explore boxes, bags, mailers and pouches.'],
 bags:['Bags & Totes','Reusable totes, drawstring bags, utility pouches and corporate laptop bags for everyday brand visibility.'],
 vehicles:['Bus & Car Branding','Explore full wraps, partial graphics, car door branding and coordinated fleet designs.'],
 office:['Office Branding','Explore reception areas, wall graphics, glass partitions and signage through WAWO and Exito catalogue concepts.'],
 events:['Events & Conferences','Build a coordinated experience with attendee packs, crew merchandise, stage graphics and event signage.']
};
const query=new URLSearchParams(location.search);const active=Object.hasOwn(categories,query.get('category'))?query.get('category'):'gifts';
const [title,description]=categories[active];document.title=title+' | WAWO Brand House';document.getElementById('title').textContent=title;document.getElementById('description').textContent=description;
for(const [id,[name]] of Object.entries(categories)){const a=document.createElement('a');a.href='collections.html?category='+id;a.textContent=name;if(id===active)a.setAttribute('aria-current','page');document.getElementById('categories').append(a);}
const entries=window.WAWO_CATALOGUE.filter(item=>item.category===active);let selected='All';const filterRoot=document.getElementById('filters');
function render(){filterRoot.replaceChildren();for(const group of ['All',...new Set(entries.map(item=>item.group))]){const b=document.createElement('button');b.type='button';b.textContent=group;b.setAttribute('aria-pressed',String(group===selected));b.addEventListener('click',()=>{selected=group;render();[...filterRoot.children].find(el=>el.textContent===group).focus();});filterRoot.append(b);}
const visible=entries.filter(item=>selected==='All'||item.group===selected);document.getElementById('count').textContent=visible.length+' options';const gallery=document.getElementById('gallery');gallery.replaceChildren();for(const item of visible){const article=document.createElement('article');article.className='card';const button=document.createElement('button');button.type='button';button.className='image-button';button.setAttribute('aria-label','View '+item.title);const img=document.createElement('img');img.src=item.image;img.alt=item.title;img.loading='lazy';img.width=item.width;img.height=item.height;const zoom=document.createElement('span');zoom.textContent='View larger';button.append(img,zoom);button.addEventListener('click',()=>{document.getElementById('viewer-title').textContent=item.title;const large=document.getElementById('viewer-image');large.src=item.image;large.alt=item.title;document.getElementById('viewer-caption').textContent=item.description;document.getElementById('viewer').showModal();});const group=document.createElement('small');group.textContent=item.group;const heading=document.createElement('h2');heading.textContent=item.title;const desc=document.createElement('p');desc.textContent=item.description;const finish=document.createElement('p');finish.className='finish';const label=document.createElement('strong');label.textContent='Branding: ';finish.append(label,document.createTextNode(item.branding));const link=document.createElement('a');link.className='enquire';link.textContent='Request a quote';link.href='index.html?product='+encodeURIComponent(item.title)+'#quote';article.append(button,group,heading,desc,finish,link);gallery.append(article);}}
render();const viewer=document.getElementById('viewer');document.getElementById('close').addEventListener('click',()=>viewer.close());viewer.addEventListener('click',event=>{if(event.target===viewer){const r=viewer.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)viewer.close();}});
